//This is where we add the PoH stuff to ERG and then intialise it

$(document).ready(function () {

    erg.game.title = "Pupeteer of Hearts";
    erg.game.author = "Jye Nicolson (aka Mengtzu)";

    erg.world[erg.constants["pohValidInitialHearts"]] = [erg.constants["pohKoakuma"], erg.constants["pohLetty"], erg.constants["pohLunasa"], erg.constants["pohMerlin"], erg.constants["pohLyrica"], erg.constants["pohRan"], erg.constants["pohMystia"], erg.constants["pohKeine"], erg.constants["pohEirin"], erg.constants["pohKaguya"], erg.constants["pohMokou"], erg.constants["pohYuuka"], erg.constants["pohEiki"], erg.constants["pohShizuha"], erg.constants["pohMinoriko"], erg.constants["pohHina"], erg.constants["pohMomiji"], erg.constants["pohKanako"], erg.constants["pohParsee"], erg.constants["pohYuugi"], erg.constants["pohRin"], erg.constants["pohKogasa"], erg.constants["pohIchirin"], erg.constants["pohMurasa"], erg.constants["pohShou"], erg.constants["pohByakuren"], erg.constants["pohNue"], erg.constants["pohHatate"], erg.constants["pohKyouko"], erg.constants["pohYoshika"], erg.constants["pohSeiga"], erg.constants["pohTojiko"], erg.constants["pohFuto"], erg.constants["pohMiko"], erg.constants["pohMamizou"], erg.constants["pohKasen"]];

    erg.world[erg.constants["pohValidRandomAttractionTraits"]] = [erg.constants["pohTraitAttractionGirlInUniform"], erg.constants["pohTraitAttractionHairLong"], erg.constants["pohTraitAttractionHairShort"], erg.constants["pohTraitAttractionHairExotic"], erg.constants["pohTraitAttractionHairTraditional"], erg.constants["pohTraitAttractionHairGold"], erg.constants["pohTraitAttractionHairWinter"], erg.constants["pohTraitAttractionHairRose"], erg.constants["pohTraitAttractionHairCool"], erg.constants["pohTraitAttractionHairLively"], erg.constants["pohTraitAttractionEyesRed"], erg.constants["pohTraitAttractionEyesCool"], erg.constants["pohTraitAttractionEyesMetallic"], erg.constants["pohTraitAttractionEyesTraditional"], erg.constants["pohTraitAttractionEyesGreen"], erg.constants["pohTraitAttractionEyesExotic"], erg.constants["pohTraitAttractionSpeciesHell"], erg.constants["pohTraitAttractionSpeciesBeast"], erg.constants["pohTraitAttractionSpeciesDead"], erg.constants["pohTraitAttractionSpeciesDivine"], erg.constants["pohTraitAttractionSpeciesUndying"], erg.constants["pohTraitAttractionSpeciesYoukai"], erg.constants["pohTraitAttractionGenericMarisa"], erg.constants["pohTraitAttractionGenericNone"], erg.constants["pohTraitAttractionTierWeak"], erg.constants["pohTraitAttractionTierEqual"], erg.constants["pohTraitAttractionTierStrong"]];

    erg.world[erg.constants["pohValidRandomReactionTraits"]] = [erg.constants["pohTraitReactionTsundere"], erg.constants["pohTraitReactionAwkwardEnvy"], erg.constants["pohTraitReactionCoward"], erg.constants["pohTraitReactionBeast"], erg.constants["pohTraitReactionNoHero"], erg.constants["pohTraitReactionNoPoet"], erg.constants["pohTraitReactionMistress"], erg.constants["pohTraitReactionVillain"], erg.constants["pohTraitReactionIntelligentsiaDistaste"], erg.constants["pohTraitReactionHeroicContempt"], erg.constants["pohTraitReactionHatredSilverTongues"], erg.constants["pohTraitReactionCarousersFoe"], erg.constants["pohTraitReactionBelovedProud"], erg.constants["pohTraitReactionGreenEyedMonster"], erg.constants["pohTraitReactionVindictiveCute"], erg.constants["pohTraitReactionLovelyMalice"], erg.constants["pohTraitReactionEgalitarian"], erg.constants["pohTraitReactionNoble"], erg.constants["pohTraitReactionEnlightened"], erg.constants["pohTraitReactionSweetHumble"], erg.constants["pohTraitReactionHero"], erg.constants["pohTraitReactionPoet"], erg.constants["pohTraitReactionNoMistress"], erg.constants["pohTraitReactionNoVillain"], erg.constants["pohTraitReactionGenius"], erg.constants["pohTraitReactionFearless"], erg.constants["pohTraitReactionMuse"], erg.constants["pohTraitReactionSocialButterfly"], erg.constants["pohTraitReactionTragedy"], erg.constants["pohTraitReactionTrust"], erg.constants["pohTraitReactionVindictiveUgly"], erg.constants["pohTraitReactionCruelty"]];

    erg.world[erg.constants["pohValidAttributes"]] = [erg.constants["pohAttributeLoneliness"], erg.constants["pohAttributeExpression"], erg.constants["pohAttributeCleverness"], erg.constants["pohAttributePettiness"], erg.constants["pohAttributeCourage"], erg.constants["pohAttributeViciousness"], erg.constants["pohAttributeSociability"], erg.constants["pohAttributeJealousy"], erg.constants["pohAttributeHubris"], erg.constants["pohAttributeReputation"]];

    erg.world[erg.constants["pohValidRandomPassionTracks"]] = [erg.constants["pohPassionTrackFriend"], erg.constants["pohPassionTrackAlly"], erg.constants["pohPassionTrackRival"], erg.constants["pohPassionTrackEnemy"], erg.constants["pohPassionTrackLove"]];

    erg.world[erg.constants["pohValidRandomDateScenarios"]] = [erg.constants["pohAttributeTestScenarioScarletChess"], erg.constants["pohAttributeTestScenarioWarpathMiko"], erg.constants["pohAttributeTestScenarioPoetryBattle"], erg.constants["pohAttributeTestScenarioHakureiParty"], erg.constants["pohAttributeTestScenarioGensokyoChronicles"], erg.constants["pohAttributeTestScenarioTripleDate"], erg.constants["pohAttributeTestScenarioYuyukoTrolling"], erg.constants["pohAttributeTestScenarioFairySquishing"], erg.constants["pohAttributeTestScenarioBorderTeam"], erg.constants["pohAttributeTestScenarioCharades"], erg.constants["pohAttributeTestScenarioTruthPatrol"], erg.constants["pohAttributeTestScenarioVillageInfluence"], erg.constants["pohAttributeTestScenarioChivalry"], erg.constants["pohAttributeTestScenarioGhostTeam"], erg.constants["pohAttributeTestScenarioCelestialTeam"], erg.constants["pohAttributeTestScenarioVampireTeam"], erg.constants["pohAttributeTestScenarioPatchouliRiddles"], erg.constants["pohAttributeTestScenarioMismatchedDanmaku"], erg.constants["pohAttributeTestScenarioSingForKomachi"], erg.constants["pohAttributeTestScenarioHakureiSakeScramble"], erg.constants["pohAttributeTestScenarioRabbits"], erg.constants["pohAttributeTestScenarioMountainBorder"], erg.constants["pohAttributeTestScenarioPenaltyGame"], erg.constants["pohAttributeTestScenarioIsThatSo"], erg.constants["pohAttributeTestScenarioTreasuresOfThePast"], erg.constants["pohAttributeTestScenarioTheGreatMovingLibrary"], erg.constants["pohAttributeTestScenarioTragicHistories"], erg.constants["pohAttributeTestScenarioDangerousChildren"], erg.constants["pohAttributeTestScenarioPlayingTheVillains"], erg.constants["pohAttributeTestScenarioForestOfMagicInfiltration"], erg.constants["pohAttributeTestScenarioDoubleDate"], erg.constants["pohAttributeTestScenarioVenom"]];

    erg.world[erg.constants["pohCandidateRandomNewsTypes"]] = [erg.constants["pohNewsTypeAdviceLetter"], erg.constants["pohNewsTypeDate"], erg.constants["pohNewsTypeAttributeChange"], erg.constants["pohNewsTypeTraitChange"], erg.constants["pohNewsTypePassionChange"], erg.constants["pohNewsTypeDanmakuMatch"]];

    erg.world[erg.constants["pohValidRandomAttributeChangeScenarios"]] = [erg.constants["pohAttributeChangeScenarioGainCleverness"], erg.constants["pohAttributeChangeScenarioGainCourage"], erg.constants["pohAttributeChangeScenarioGainExpression"], erg.constants["pohAttributeChangeScenarioGainSociability"], erg.constants["pohAttributeChangeScenarioGainHubris"], erg.constants["pohAttributeChangeScenarioGainJealousy"], erg.constants["pohAttributeChangeScenarioGainPettiness"], erg.constants["pohAttributeChangeScenarioGainViciousness"], erg.constants["pohAttributeChangeScenarioGainLoneliness"], erg.constants["pohAttributeChangeScenarioLoseCleverness"], erg.constants["pohAttributeChangeScenarioLoseCourage"], erg.constants["pohAttributeChangeScenarioLoseExpression"], erg.constants["pohAttributeChangeScenarioLoseSociability"], erg.constants["pohAttributeChangeScenarioLoseHubris"], erg.constants["pohAttributeChangeScenarioLoseJealousy"], erg.constants["pohAttributeChangeScenarioLosePettiness"], erg.constants["pohAttributeChangeScenarioLoseViciousness"], erg.constants["pohAttributeChangeScenarioLoseLoneliness"]];

    erg.event(erg.constants["eventPoHTitleScreen"]);

});